spring:
  datasource:
    url: jdbc:h2:mem:bankDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console



flyway:
  enabled: true
  encoding: UTF-8
  locations: classpath:db/migration
  out-of-order: false
  baseline-on-migrate: true
  baseline-version: 0

spring-doc:
  api-docs:
    path: /bank-docs
  swagger-ui:
    path: /swagger-ui-custom.html